<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC7425" failures="0" tests="7" name="sumo.qa.testcases.FrontpageTest" time="0.001" errors="1" timestamp="30 Sep 2019 14:11:41 GMT" skipped="6">
  <testcase classname="sumo.qa.testcases.FrontpageTest" name="setUp" time="0.001">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at sumo.qa.base.TestBase.initialization(TestBase.java:86)
at sumo.qa.testcases.FrontpageTest.setUp(FrontpageTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="sumo.qa.testcases.FrontpageTest" name="LogginnFunction_Test" time="0.000">
    <skipped/>
  </testcase> <!-- LogginnFunction_Test -->
  <testcase classname="sumo.qa.testcases.FrontpageTest" name="GlemtPassordLink_Click_Test" time="0.000">
    <skipped/>
  </testcase> <!-- GlemtPassordLink_Click_Test -->
  <testcase classname="sumo.qa.testcases.FrontpageTest" name="NyBruker_FaatilgangNaaLink_Test" time="0.000">
    <skipped/>
  </testcase> <!-- NyBruker_FaatilgangNaaLink_Test -->
  <testcase classname="sumo.qa.testcases.FrontpageTest" name="logginnBtn_Click_Test" time="0.000">
    <skipped/>
  </testcase> <!-- logginnBtn_Click_Test -->
  <testcase classname="sumo.qa.testcases.FrontpageTest" name="LogginnAvbrytBtn_Click_Test" time="0.000">
    <skipped/>
  </testcase> <!-- LogginnAvbrytBtn_Click_Test -->
  <testcase classname="sumo.qa.testcases.FrontpageTest" name="SumoLogo_Click_Test" time="0.000">
    <skipped/>
  </testcase> <!-- SumoLogo_Click_Test -->
</testsuite> <!-- sumo.qa.testcases.FrontpageTest -->
